FROM node:10-alpine

RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app
WORKDIR /home/node/app

COPY --chown=node:node package*.json ./

RUN npm install
RUN npm install -g sequelize-cli
# RUN ./node_modules/typescript/bin/tsc

# COPY --chown=node:node bin ./bin/
COPY bin ./bin/
COPY config ./config/
COPY migrations ./migrations/
RUN cd bin
RUN sequelize db:migrate --config config/config.json --env development --models-path src/models
RUN cd ..

EXPOSE 8080
# USER node
CMD [ "node", "bin/index.js" ]